name: elearnapp
description: Collaborate with your colleages, students, teachers or parents through an effective medium

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_statusbarcolor: 0.2.3
  shared_preferences: 0.5.6+3
  curved_navigation_bar: 0.3.2
  badges: 1.1.1
  touchable_opacity: 1.1.0
  pull_to_refresh: 1.5.8
  font_awesome_flutter: 8.8.1
  hexcolor: 1.0.1
  email_validator: '^1.0.0'
  provider: ^3.1.0
  firebase_auth: 0.15.5+3
  cloud_firestore: 0.13.4+2
  firebase_storage: 3.1.5
  flutter_breadcrumb: ^0.1.2
  faker: 1.2.1
  fluttertoast: ^4.0.0
  grouped_buttons: 1.0.4
  timeago: 2.0.26
  wakelock: 0.1.4+1
  unicode: 0.2.3
  shimmer: 1.1.1
  cached_network_image: 2.1.0+1
  scroll_snap_list: 0.4.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/product-regular.ttf
        - asset: assets/fonts/product-bold.ttf
    - family: Number
      fonts:
        - asset: assets/fonts/consola.ttf
